// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX6S09pT5Sf9T7I5tL9MnHpBDgeg3gOBs',
    appId: '1:1044233619556:web:c1623bb66ae4cf7d3ef771',
    messagingSenderId: '1044233619556',
    projectId: 'findpet-8499e',
    authDomain: 'findpet-8499e.firebaseapp.com',
    storageBucket: 'findpet-8499e.appspot.com',
    measurementId: 'G-RK7ZEZEKSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyCg7TO04r6buj-WgpGe36YYn2H2whseY',
    appId: '1:1044233619556:android:2bad2b51b69cdb353ef771',
    messagingSenderId: '1044233619556',
    projectId: 'findpet-8499e',
    storageBucket: 'findpet-8499e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIz2-2V82n2q9vJZJFEZK6cYxsr0lVCo8',
    appId: '1:1044233619556:ios:7eb1ebfab234683c3ef771',
    messagingSenderId: '1044233619556',
    projectId: 'findpet-8499e',
    storageBucket: 'findpet-8499e.appspot.com',
    androidClientId: '1044233619556-9ommb23pc616ubs9nms62dpdqa6asbfj.apps.googleusercontent.com',
    iosClientId: '1044233619556-2cbaqsgqhkc6j68b8plbkkc7keda0r5p.apps.googleusercontent.com',
    iosBundleId: 'com.etec094.findpet',
  );
}
